-- INSERT DATA FOR STARSHIP MISSION MANAGEMENT SYSTEM

-- STARSHIP
INSERT INTO STARSHIP VALUES (1,'SN100','01-JAN-20','ACTIVE',5);
INSERT INTO STARSHIP VALUES (2,'SN101','15-FEB-20','ACTIVE',3);
INSERT INTO STARSHIP VALUES (3,'SN102','10-MAR-21','INACTIVE',1);

-- BOOSTER
INSERT INTO BOOSTER VALUES (1,'B100',7600,'05-JAN-20','ACTIVE');
INSERT INTO BOOSTER VALUES (2,'B101',7500,'20-FEB-20','ACTIVE');
INSERT INTO BOOSTER VALUES (3,'B102',7700,'12-MAR-21','INACTIVE');

-- LAUNCHSITE
INSERT INTO LAUNCHSITE VALUES (1,'KENNEDY SPACE CENTER','FLORIDA','USA',10);
INSERT INTO LAUNCHSITE VALUES (2,'VANDENBERG','CALIFORNIA','USA',8);
INSERT INTO LAUNCHSITE VALUES (3,'STARBASE','TEXAS','USA',12);

-- CREWMEMBER
INSERT INTO CREWMEMBER VALUES (1,'JOHN','DOE','USA','COMMANDER',10);
INSERT INTO CREWMEMBER VALUES (2,'ALICE','SMITH','UK','PILOT',8);
INSERT INTO CREWMEMBER VALUES (3,'RAHUL','SHARMA','INDIA','ENGINEER',6);
INSERT INTO CREWMEMBER VALUES (4,'MARIA','GARCIA','SPAIN','SCIENTIST',7);
INSERT INTO CREWMEMBER VALUES (5,'LEE','CHAN','CHINA','SPECIALIST',5);

-- PAYLOAD
INSERT INTO PAYLOAD VALUES (1,'STARLINK SAT',500,'SATELLITE','SPACEX');
INSERT INTO PAYLOAD VALUES (2,'GPS MODULE',300,'NAVIGATION','NASA');
INSERT INTO PAYLOAD VALUES (3,'RESEARCH KIT',200,'SCIENCE','ESA');
INSERT INTO PAYLOAD VALUES (4,'SUPPLY CARGO',800,'CARGO','ISRO');

-- MISSION
INSERT INTO MISSION VALUES (1,'MISSION ALPHA','10-JAN-22','ORBITAL','SUCCESS','LEO',1,1,1);
INSERT INTO MISSION VALUES (2,'MISSION BETA','20-FEB-22','RESUPPLY','SUCCESS','ISS',2,2,2);
INSERT INTO MISSION VALUES (3,'MISSION GAMMA','15-MAR-22','TEST','FAILED','SUBORBITAL',3,3,3);
INSERT INTO MISSION VALUES (4,'MISSION DELTA','01-APR-22','RESEARCH','SUCCESS','LEO',1,2,3);

-- CREW_PHONE
INSERT INTO CREW_PHONE VALUES (1,'9876543210');
INSERT INTO CREW_PHONE VALUES (1,'9123456780');
INSERT INTO CREW_PHONE VALUES (2,'9988776655');
INSERT INTO CREW_PHONE VALUES (3,'9090909090');
INSERT INTO CREW_PHONE VALUES (4,'8888888888');
INSERT INTO CREW_PHONE VALUES (5,'7777777777');

-- LAUNCH_ATTEMPT
INSERT INTO LAUNCH_ATTEMPT VALUES (1,1,'10-JAN-22','SUCCESS','CLEAR');
INSERT INTO LAUNCH_ATTEMPT VALUES (2,1,'20-FEB-22','SUCCESS','CLOUDY');
INSERT INTO LAUNCH_ATTEMPT VALUES (3,1,'15-MAR-22','FAILED','RAIN');
INSERT INTO LAUNCH_ATTEMPT VALUES (3,2,'16-MAR-22','SUCCESS','CLEAR');
INSERT INTO LAUNCH_ATTEMPT VALUES (4,1,'01-APR-22','SUCCESS','CLEAR');

-- MAINTENANCE_RECORD
INSERT INTO MAINTENANCE_RECORD VALUES (1,1,'01-FEB-22','ENGINE CHECK','MIKE');
INSERT INTO MAINTENANCE_RECORD VALUES (1,2,'01-MAR-22','FUEL SYSTEM','JOHN');
INSERT INTO MAINTENANCE_RECORD VALUES (2,1,'05-MAR-22','BOOSTER FIX','ALICE');
INSERT INTO MAINTENANCE_RECORD VALUES (3,1,'10-MAR-22','STRUCTURE CHECK','RAHUL');

-- MISSION_CREW
INSERT INTO MISSION_CREW VALUES (1,1);
INSERT INTO MISSION_CREW VALUES (1,2);
INSERT INTO MISSION_CREW VALUES (2,3);
INSERT INTO MISSION_CREW VALUES (2,4);
INSERT INTO MISSION_CREW VALUES (3,5);
INSERT INTO MISSION_CREW VALUES (4,1);

-- MISSION_PAYLOAD
INSERT INTO MISSION_PAYLOAD VALUES (1,1);
INSERT INTO MISSION_PAYLOAD VALUES (1,2);
INSERT INTO MISSION_PAYLOAD VALUES (2,3);
INSERT INTO MISSION_PAYLOAD VALUES (3,4);
INSERT INTO MISSION_PAYLOAD VALUES (4,1);

COMMIT;
