-- SEED SQL FILE FOR STARSHIP MISSION MANAGEMENT SYSTEM

CREATE TABLE STARSHIP (
	STARSHIPID NUMBER PRIMARY KEY,
	SERIALNUMBER VARCHAR2(50),
	BUILDDATE DATE,
	STATUS VARCHAR2(20),
	TOTALFLIGHTS NUMBER
);

CREATE TABLE BOOSTER (
	BOOSTERID NUMBER PRIMARY KEY,
	SERIALNUMBER VARCHAR2(50),
	THRUSTCAPACITY NUMBER,
	BUILDDATE DATE,
	STATUS VARCHAR2(20)
);

CREATE TABLE LAUNCHSITE (
	SITEID NUMBER PRIMARY KEY,
	SITENAME VARCHAR2(100),
	CITY VARCHAR2(50),
	COUNTRY VARCHAR2(50),
	CAPACITY NUMBER
);

CREATE TABLE MISSION (
	MISSIONID NUMBER PRIMARY KEY,
	MISSIONNAME VARCHAR2(100),
	LAUNCHDATE DATE,
	MISSIONTYPE VARCHAR2(50),
	STATUS VARCHAR2(50),
	ORBITTYPE VARCHAR2(50),
	STARSHIPID NUMBER,
	BOOSTERID NUMBER,
	SITEID NUMBER,
	FOREIGN KEY (STARSHIPID) REFERENCES STARSHIP(STARSHIPID),
	FOREIGN KEY (BOOSTERID) REFERENCES BOOSTER(BOOSTERID),
	FOREIGN KEY (SITEID) REFERENCES LAUNCHSITE(SITEID)
);

CREATE TABLE CREWMEMBER (
	CREWID NUMBER PRIMARY KEY,
	FIRSTNAME VARCHAR2(50),
	LASTNAME VARCHAR2(50),
	NATIONALITY VARCHAR2(50),
	ROLE VARCHAR2(50),
	EXPERIENCEYEARS NUMBER
);

CREATE TABLE CREW_PHONE (
	CREWID NUMBER,
	PHONENUMBER VARCHAR2(15),
	PRIMARY KEY (CREWID, PHONENUMBER),
	FOREIGN KEY (CREWID) REFERENCES CREWMEMBER(CREWID)
);

CREATE TABLE PAYLOAD (
	PAYLOADID NUMBER PRIMARY KEY,
	PAYLOADNAME VARCHAR2(100),
	WEIGHT NUMBER,
	TYPE VARCHAR2(50),
	OWNERORGANIZATION VARCHAR2(100)
);

CREATE TABLE LAUNCH_ATTEMPT (
	MISSIONID NUMBER,
	ATTEMPTNUMBER NUMBER,
	ATTEMPTDATE DATE,
	OUTCOME VARCHAR2(20),
	WEATHERCONDITION VARCHAR2(50),
	PRIMARY KEY (MISSIONID, ATTEMPTNUMBER),
	FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID)
);

CREATE TABLE MAINTENANCE_RECORD (
	STARSHIPID NUMBER,
	MAINT_ID NUMBER,
	MAINT_DATE DATE,
	MAINT_DESC VARCHAR2(4000),
	ENGINEERNAME VARCHAR2(100),
	PRIMARY KEY (STARSHIPID, MAINT_ID),
	FOREIGN KEY (STARSHIPID) REFERENCES STARSHIP(STARSHIPID)
);

CREATE TABLE MISSION_CREW (
	MISSIONID NUMBER,
	CREWID NUMBER,
	PRIMARY KEY (MISSIONID, CREWID),
	FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID),
	FOREIGN KEY (CREWID) REFERENCES CREWMEMBER(CREWID)
);

CREATE TABLE MISSION_PAYLOAD (
	MISSIONID NUMBER,
	PAYLOADID NUMBER,
	PRIMARY KEY (MISSIONID, PAYLOADID),
	FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID),
	FOREIGN KEY (PAYLOADID) REFERENCES PAYLOAD(PAYLOADID)
);
