-- ============================================================
-- STARSHIP MMS — Oracle Setup Script
-- Run this ONCE in SQL*Plus before starting the Flask backend
--
-- HOW TO RUN:
--   1. Open SQL*Plus
--   2. Connect: CONNECT system/tiger  (or your username/password)
--   3. Run:     @setup_oracle.sql
--      OR paste the whole file and press Enter
-- ============================================================


-- ─────────────────────────────────────────────
-- STEP 1: Drop tables (in reverse FK order)
-- Safe to run even if tables don't exist yet
-- ─────────────────────────────────────────────

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MISSION_CREW      CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MISSION_PAYLOAD   CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAUNCH_ATTEMPT    CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE_RECORD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CREW_PHONE        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MISSION           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CREWMEMBER        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAYLOAD           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAUNCHSITE        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BOOSTER           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STARSHIP          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STARSHIP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOOSTER';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SITE';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MISSION';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CREW';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAYLOAD';  EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ─────────────────────────────────────────────
-- STEP 2: Create Sequences (auto-increment IDs)
-- ─────────────────────────────────────────────

CREATE SEQUENCE SEQ_STARSHIP START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOOSTER  START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SITE     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MISSION  START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CREW     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYLOAD  START WITH 100 INCREMENT BY 1;


-- ─────────────────────────────────────────────
-- STEP 3: Create Tables (same as your DA2 schema)
-- ─────────────────────────────────────────────

CREATE TABLE STARSHIP (
    STARSHIPID   NUMBER PRIMARY KEY,
    SERIALNUMBER VARCHAR2(50),
    BUILDDATE    DATE,
    STATUS       VARCHAR2(20),
    TOTALFLIGHTS NUMBER DEFAULT 0
);

CREATE TABLE BOOSTER (
    BOOSTERID      NUMBER PRIMARY KEY,
    SERIALNUMBER   VARCHAR2(50),
    THRUSTCAPACITY NUMBER,
    BUILDDATE      DATE,
    STATUS         VARCHAR2(20)
);

CREATE TABLE LAUNCHSITE (
    SITEID   NUMBER PRIMARY KEY,
    SITENAME VARCHAR2(100),
    CITY     VARCHAR2(50),
    COUNTRY  VARCHAR2(50),
    CAPACITY NUMBER
);

CREATE TABLE MISSION (
    MISSIONID   NUMBER PRIMARY KEY,
    MISSIONNAME VARCHAR2(100),
    LAUNCHDATE  DATE,
    MISSIONTYPE VARCHAR2(50),
    STATUS      VARCHAR2(50),
    ORBITTYPE   VARCHAR2(50),
    STARSHIPID  NUMBER,
    BOOSTERID   NUMBER,
    SITEID      NUMBER,
    FOREIGN KEY (STARSHIPID) REFERENCES STARSHIP(STARSHIPID),
    FOREIGN KEY (BOOSTERID)  REFERENCES BOOSTER(BOOSTERID),
    FOREIGN KEY (SITEID)     REFERENCES LAUNCHSITE(SITEID)
);

CREATE TABLE CREWMEMBER (
    CREWID          NUMBER PRIMARY KEY,
    FIRSTNAME       VARCHAR2(50),
    LASTNAME        VARCHAR2(50),
    NATIONALITY     VARCHAR2(50),
    ROLE            VARCHAR2(50),
    EXPERIENCEYEARS NUMBER DEFAULT 0
);

CREATE TABLE CREW_PHONE (
    CREWID      NUMBER,
    PHONENUMBER VARCHAR2(15),
    PRIMARY KEY (CREWID, PHONENUMBER),
    FOREIGN KEY (CREWID) REFERENCES CREWMEMBER(CREWID)
);

CREATE TABLE PAYLOAD (
    PAYLOADID         NUMBER PRIMARY KEY,
    PAYLOADNAME       VARCHAR2(100),
    WEIGHT            NUMBER,
    TYPE              VARCHAR2(50),
    OWNERORGANIZATION VARCHAR2(100)
);

CREATE TABLE LAUNCH_ATTEMPT (
    MISSIONID        NUMBER,
    ATTEMPTNUMBER    NUMBER,
    ATTEMPTDATE      DATE,
    OUTCOME          VARCHAR2(20),
    WEATHERCONDITION VARCHAR2(50),
    PRIMARY KEY (MISSIONID, ATTEMPTNUMBER),
    FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID)
);

CREATE TABLE MAINTENANCE_RECORD (
    STARSHIPID   NUMBER,
    MAINT_ID     NUMBER,
    MAINT_DATE   DATE,
    MAINT_DESC   VARCHAR2(4000),
    ENGINEERNAME VARCHAR2(100),
    PRIMARY KEY (STARSHIPID, MAINT_ID),
    FOREIGN KEY (STARSHIPID) REFERENCES STARSHIP(STARSHIPID)
);

CREATE TABLE MISSION_CREW (
    MISSIONID NUMBER,
    CREWID    NUMBER,
    PRIMARY KEY (MISSIONID, CREWID),
    FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID),
    FOREIGN KEY (CREWID)    REFERENCES CREWMEMBER(CREWID)
);

CREATE TABLE MISSION_PAYLOAD (
    MISSIONID NUMBER,
    PAYLOADID NUMBER,
    PRIMARY KEY (MISSIONID, PAYLOADID),
    FOREIGN KEY (MISSIONID) REFERENCES MISSION(MISSIONID),
    FOREIGN KEY (PAYLOADID) REFERENCES PAYLOAD(PAYLOADID)
);


-- ─────────────────────────────────────────────
-- STEP 4: Insert Sample Data
-- ─────────────────────────────────────────────

INSERT INTO STARSHIP VALUES (SEQ_STARSHIP.NEXTVAL, 'SN100', TO_DATE('01-JAN-20','DD-MON-YY'), 'ACTIVE',   5);
INSERT INTO STARSHIP VALUES (SEQ_STARSHIP.NEXTVAL, 'SN101', TO_DATE('15-FEB-20','DD-MON-YY'), 'ACTIVE',   3);
INSERT INTO STARSHIP VALUES (SEQ_STARSHIP.NEXTVAL, 'SN102', TO_DATE('10-MAR-21','DD-MON-YY'), 'INACTIVE', 1);

INSERT INTO BOOSTER VALUES (SEQ_BOOSTER.NEXTVAL, 'B100', 7600, TO_DATE('05-JAN-20','DD-MON-YY'), 'ACTIVE');
INSERT INTO BOOSTER VALUES (SEQ_BOOSTER.NEXTVAL, 'B101', 7500, TO_DATE('20-FEB-20','DD-MON-YY'), 'ACTIVE');
INSERT INTO BOOSTER VALUES (SEQ_BOOSTER.NEXTVAL, 'B102', 7700, TO_DATE('12-MAR-21','DD-MON-YY'), 'INACTIVE');

INSERT INTO LAUNCHSITE VALUES (SEQ_SITE.NEXTVAL, 'Starbase',   'Boca Chica',      'USA', 10);
INSERT INTO LAUNCHSITE VALUES (SEQ_SITE.NEXTVAL, 'LC-39A',     'Cape Canaveral',  'USA', 20);
INSERT INTO LAUNCHSITE VALUES (SEQ_SITE.NEXTVAL, 'SLC-4E',     'Vandenberg',      'USA',  8);

-- Note: IDs start at 100 from our sequences.
-- Starships: 100,101,102 | Boosters: 100,101,102 | Sites: 100,101,102

INSERT INTO MISSION VALUES (SEQ_MISSION.NEXTVAL,'Artemis Alpha',   TO_DATE('01-MAR-24','DD-MON-YY'),'Lunar',         'Completed','Lunar', 100,100,100);
INSERT INTO MISSION VALUES (SEQ_MISSION.NEXTVAL,'Starlink Surge',  TO_DATE('15-JUN-24','DD-MON-YY'),'Satellite',     'Active',   'LEO',   101,101,101);
INSERT INTO MISSION VALUES (SEQ_MISSION.NEXTVAL,'Mars Pathfinder', TO_DATE('20-JAN-25','DD-MON-YY'),'Interplanetary','Planned',  'TMI',   100,100,100);
INSERT INTO MISSION VALUES (SEQ_MISSION.NEXTVAL,'Polar Recon',     TO_DATE('10-SEP-24','DD-MON-YY'),'Science',       'Completed','Polar', 101,101,102);

INSERT INTO CREWMEMBER VALUES (SEQ_CREW.NEXTVAL,'Elena', 'Vasquez','USA',    'Commander',       12);
INSERT INTO CREWMEMBER VALUES (SEQ_CREW.NEXTVAL,'Yuki',  'Tanaka', 'Japan',  'Pilot',            8);
INSERT INTO CREWMEMBER VALUES (SEQ_CREW.NEXTVAL,'Rajan', 'Mehta',  'India',  'Engineer',         6);
INSERT INTO CREWMEMBER VALUES (SEQ_CREW.NEXTVAL,'Sofia', 'Novak',  'Germany','Scientist',        5);
INSERT INTO CREWMEMBER VALUES (SEQ_CREW.NEXTVAL,'Marcus','Stone',  'UK',     'Medic',            4);

INSERT INTO PAYLOAD VALUES (SEQ_PAYLOAD.NEXTVAL,'Starlink V2 Batch',22000,'Satellite','SpaceX');
INSERT INTO PAYLOAD VALUES (SEQ_PAYLOAD.NEXTVAL,'Lunar Rover Mk2',   1200,'Rover',    'NASA');
INSERT INTO PAYLOAD VALUES (SEQ_PAYLOAD.NEXTVAL,'Mars Habitat Core', 15000,'Habitat',  'NASA');
INSERT INTO PAYLOAD VALUES (SEQ_PAYLOAD.NEXTVAL,'Earth Obs Sensor',   800,'Sensor',   'ESA');

-- Missions: 100,101,102,103 | Crew: 100-104 | Payloads: 100-103

INSERT INTO LAUNCH_ATTEMPT VALUES (100,1,TO_DATE('01-MAR-24','DD-MON-YY'),'SUCCESS','Clear');
INSERT INTO LAUNCH_ATTEMPT VALUES (101,1,TO_DATE('14-JUN-24','DD-MON-YY'),'ABORT',  'Thunderstorm');
INSERT INTO LAUNCH_ATTEMPT VALUES (101,2,TO_DATE('15-JUN-24','DD-MON-YY'),'SUCCESS','Clear');
INSERT INTO LAUNCH_ATTEMPT VALUES (103,1,TO_DATE('10-SEP-24','DD-MON-YY'),'SUCCESS','Partly Cloudy');

INSERT INTO MAINTENANCE_RECORD VALUES (100,1,TO_DATE('10-JAN-24','DD-MON-YY'),'Engine TPS inspection',  'Dr. Kim');
INSERT INTO MAINTENANCE_RECORD VALUES (100,2,TO_DATE('22-FEB-24','DD-MON-YY'),'Heat shield replacement','L. Garza');
INSERT INTO MAINTENANCE_RECORD VALUES (101,1,TO_DATE('05-MAY-24','DD-MON-YY'),'Avionics upgrade',       'T. Brooks');
INSERT INTO MAINTENANCE_RECORD VALUES (102,1,TO_DATE('18-JUL-24','DD-MON-YY'),'Full refurbishment',     'Dr. Kim');

INSERT INTO MISSION_CREW VALUES (100,100);
INSERT INTO MISSION_CREW VALUES (100,101);
INSERT INTO MISSION_CREW VALUES (100,102);
INSERT INTO MISSION_CREW VALUES (101,103);
INSERT INTO MISSION_CREW VALUES (103,100);
INSERT INTO MISSION_CREW VALUES (103,104);

INSERT INTO MISSION_PAYLOAD VALUES (100,101);
INSERT INTO MISSION_PAYLOAD VALUES (101,100);
INSERT INTO MISSION_PAYLOAD VALUES (102,102);
INSERT INTO MISSION_PAYLOAD VALUES (103,103);

COMMIT;

-- ─────────────────────────────────────────────
-- STEP 5: Verify
-- ─────────────────────────────────────────────

SELECT 'STARSHIP'          AS TABLE_NAME, COUNT(*) AS ROWS FROM STARSHIP          UNION ALL
SELECT 'BOOSTER',          COUNT(*) FROM BOOSTER                                  UNION ALL
SELECT 'LAUNCHSITE',       COUNT(*) FROM LAUNCHSITE                               UNION ALL
SELECT 'MISSION',          COUNT(*) FROM MISSION                                  UNION ALL
SELECT 'CREWMEMBER',       COUNT(*) FROM CREWMEMBER                               UNION ALL
SELECT 'PAYLOAD',          COUNT(*) FROM PAYLOAD                                  UNION ALL
SELECT 'LAUNCH_ATTEMPT',   COUNT(*) FROM LAUNCH_ATTEMPT                           UNION ALL
SELECT 'MAINTENANCE_RECORD', COUNT(*) FROM MAINTENANCE_RECORD                     UNION ALL
SELECT 'MISSION_CREW',     COUNT(*) FROM MISSION_CREW                             UNION ALL
SELECT 'MISSION_PAYLOAD',  COUNT(*) FROM MISSION_PAYLOAD;

-- You should see row counts for all 10 tables above.
-- Setup complete! Now run the Flask backend.
